name = "cronapihandler"
main = "src/index.ts"
compatibility_date = "2022-08-01"
node_compat = true
kv_namespaces = [
    { binding = "portfolio_data", id = "584c11ee12514f77a3a60809d42a9c96", preview_id = "8e8f8fecaa304a21a2a22d8372cbba34" }
]

[triggers]
crons = [ "*/1 * * * *" ]