version: "3"
services:  
  client:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - webnet
    # env_file:
    #   - "./client/.env"
    depends_on:
      - server
  server:
    build:
      context: server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    networks:
      - webnet  
    # env_file: 
    #   - "./server/rocket.env"
networks:
  webnet: