version: "3"
services:  
  db:
    image: postgres
    networks: 
      - webnet
    environment:
      POSTGRES_PASSWORD: ${PSQL_PASS}
      POSTGRES_DB: ${PSQL_DB}
      POSTGRES_INITDB_ARGS: "-A md5"
  panel:
    build: 
      context: aws_api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - webnet
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on: 
      - db
networks:
  webnet: