version: "3"
services:  
  db:
    image: postgres
    networks: 
      - webnet
    environment:
      POSTGRES_PASSWORD: ${PSQL_PASS}
      POSTGRES_DB: ${PSQL_DB}
      POSTGRES_INITDB_ARGS: "-A md5"
  gateway:
    build:
      context: client_api
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    networks:
      - webnet  
    env_file: 
      - "./client_api/src.env"
    depends_on: 
      - db    
  panel:
    build: 
      context: aws_api
      dockerfile: Dockerfile
    # restart: always
    ports:
      - "8080:8080"
    networks:
      - webnet
    env_file: 
      - "./aws_api/.env"
    depends_on: 
      - db
  nginx:
    image: nginx
    ports:
      - "80:80"
    networks:
      - webnet
    depends_on:
      - gateway
      - panel
networks:
  webnet: